export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ANSWER = "SET_ANSWER";
export const SET_TIME_REMAINING = "SET_TIME_REMAINING";

