export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ANSWER = "SET_ANSWER";
export const SET_TIME_REMAINING = "SET_TIME_REMAINING";
export const INC_PLAYABLE_SONG_COUNT = "INC_PLAYABLE_SONG_COUNT";
export const RESET_PLAYABLE_SONG_COUNT = "RESET_PLAYABLE_SONG_COUNT";
export const LOAD_SONG_LIST = "LOAD_SONG_LIST";
export const REMOVE_SONG_LIST = "REMOVE_SONG_LIST";
export const INC_TOTAL_SCORE = "INC_TOTAL_SCORE";
export const RESET_SCORE = "RESET_SCORE";

